Flask==0.11.1
attrdict==2.0.0
eventlet==0.19.0
python-socketio==1.6.1
numpy==1.13.1
Pillow==2.2.1
scipy==0.19.1
keras==2.0.8
tensorflow==1.3.0
h5py==2.6.0
(28980) wsgi starting up on http://0.0.0.0:4567
Traceback (most recent call last):
  File "/home/student/Desktop/SDCND_system_integration/ros/src/tl_detector/tl_detector.py", line 174, in <module>
    TLDetector()
  File "/home/student/Desktop/SDCND_system_integration/ros/src/tl_detector/tl_detector.py", line 47, in __init__
    self.light_classifier = TLClassifier()
  File "/home/student/Desktop/SDCND_system_integration/ros/src/tl_detector/light_classification/tl_classifier.py", line 38, in __init__
    self.serialized_graph = fid.read()
  File "/home/student/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/home/student/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/student/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/student/SDCND_system_integration/ros/src/tl_detector/light_classification/models/simulator_inference_graph/frozen_inference_graph.pb


[ERROR] [1549882405.338845]: bad callback: <bound method TLDetector.image_cb of <__main__.TLDetector object at 0x7f473131edd0>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/student/Desktop/SDCND_system_integration/ros/src/tl_detector/tl_detector.py", line 79, in image_cb
    light_wp, state = self.process_traffic_lights()
  File "/home/student/Desktop/SDCND_system_integration/ros/src/tl_detector/tl_detector.py", line 167, in process_traffic_lights
    state = self.get_light_state(light)
  File "/home/student/Desktop/SDCND_system_integration/ros/src/tl_detector/tl_detector.py", line 134, in get_light_state
    return self.light_classifier.get_classification(cv_image)
  File "/home/student/Desktop/SDCND_system_integration/ros/src/tl_detector/light_classification/tl_classifier.py", line 154, in get_classification
    if class_name == 'Red':
UnboundLocalError: local variable 'class_name' referenced before assignment



